### ISSUE TITLE
画像投稿周り

### ISSUE THREAD

**Issue by AC3ROZ** [kyoppie/kyoppie-web#20]
本文なしで画像だけの投稿ができないのは仕様ですか？

**Comment by Petitsurume** [comment]
API側でそうなっているので仕様です。
あと、webはガワを用意してるだけなのでkyoppieの機能についてはapi側にissueを立てるか、わからなかったら[kyoppie/kyoppie](https://github.com/kyoppie/kyoppie)へissueを立ててください。
