### ISSUE TITLE
adminだった場合メニューに/adminへのナビゲーションを追加

### ISSUE THREAD

**Issue by otofune** [kyoppie/kyoppie-web#32]
気分で`/admin`って打ったら入れたけどわからん

**Comment by otofune** [comment]
実装したのでいい感じにPRします
![image](https://cloud.githubusercontent.com/assets/15062473/22948972/e284768a-f343-11e6-9256-e361e88d977c.png)

**Comment by Petitsurume** [comment]
https://github.com/kyoppie/kyoppieでもういっかいやってほしい

**Comment by otofune** [comment]
マジか、かなしい
